# Generated by Django 4.2 on 2023-12-12 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_alter_fruit_price_alter_sale_total_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='fruit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sales.fruit'),
        ),
    ]
