# Generated by Django 4.2 on 2023-12-12 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_alter_sale_fruit'),
    ]

    operations = [
        migrations.AddField(
            model_name='fruit',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='fruit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.fruit'),
        ),
    ]
